table! {
    /// Representation of the `drives` table.
    ///
    /// (Automatically generated by Diesel.)
    drives (id) {
        /// The `id` column of the `drives` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `page_token` column of the `drives` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        page_token -> Text,
    }
}

table! {
    /// Representation of the `file_changelog` table.
    ///
    /// (Automatically generated by Diesel.)
    file_changelog (id, drive_id, deleted) {
        /// The `id` column of the `file_changelog` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `drive_id` column of the `file_changelog` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        drive_id -> Text,
        /// The `deleted` column of the `file_changelog` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        deleted -> Bool,
        /// The `name` column of the `file_changelog` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `trashed` column of the `file_changelog` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        trashed -> Bool,
        /// The `parent` column of the `file_changelog` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        parent -> Text,
        /// The `md5` column of the `file_changelog` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        md5 -> Text,
        /// The `size` column of the `file_changelog` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        size -> BigInt,
    }
}

table! {
    /// Representation of the `files` table.
    ///
    /// (Automatically generated by Diesel.)
    files (id, drive_id) {
        /// The `id` column of the `files` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `drive_id` column of the `files` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        drive_id -> Text,
        /// The `name` column of the `files` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `trashed` column of the `files` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        trashed -> Bool,
        /// The `parent` column of the `files` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        parent -> Text,
        /// The `md5` column of the `files` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        md5 -> Text,
        /// The `size` column of the `files` table.
        ///
        /// Its SQL type is `BigInt`.
        ///
        /// (Automatically generated by Diesel.)
        size -> BigInt,
    }
}

table! {
    /// Representation of the `folder_changelog` table.
    ///
    /// (Automatically generated by Diesel.)
    folder_changelog (id, drive_id, deleted) {
        /// The `id` column of the `folder_changelog` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `drive_id` column of the `folder_changelog` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        drive_id -> Text,
        /// The `deleted` column of the `folder_changelog` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        deleted -> Bool,
        /// The `name` column of the `folder_changelog` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `trashed` column of the `folder_changelog` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        trashed -> Bool,
        /// The `parent` column of the `folder_changelog` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        parent -> Nullable<Text>,
    }
}

table! {
    /// Representation of the `folders` table.
    ///
    /// (Automatically generated by Diesel.)
    folders (id, drive_id) {
        /// The `id` column of the `folders` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Text,
        /// The `drive_id` column of the `folders` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        drive_id -> Text,
        /// The `name` column of the `folders` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `trashed` column of the `folders` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        trashed -> Bool,
        /// The `parent` column of the `folders` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        parent -> Nullable<Text>,
    }
}

table! {
    /// Representation of the `path_changelog` view.
    path_changelog (id, drive_id, deleted) {
        /// The `id` column of the `path_changelog` view.
        ///
        /// Its SQL type is `Text`.
        id -> Text,
        /// The `drive_id` column of the `path_changelog` view.
        ///
        /// Its SQL type is `Text`.
        drive_id -> Text,
        /// The `deleted` column of the `path_changelog` table.
        ///
        /// Its SQL type is `Bool`.
        deleted -> Bool,
        /// The `path` column of the `path_changelog` view.
        ///
        /// Its SQL type is `Text`.
        path -> Text,
    }
}

table! {
    /// Representation of the `paths` view.
    paths (id, drive_id) {
        /// The `id` column of the `paths` view.
        ///
        /// Its SQL type is `Text`.
        id -> Text,
        /// The `drive_id` column of the `paths` view.
        ///
        /// Its SQL type is `Text`.
        drive_id -> Text,
        /// The `path` column of the `paths` view.
        ///
        /// Its SQL type is `Text`.
        path -> Text,
    }
}

joinable!(files -> drives (drive_id));
joinable!(folders -> drives (drive_id));

allow_tables_to_appear_in_same_query!(
    drives,
    file_changelog,
    files,
    folder_changelog,
    folders,
    path_changelog,
    paths,
);
